project 'SideChore.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideChore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'
  
  
  # Pods for SideChore

  
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]
  
  #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  
  pod 'FBSDKCoreKit', '~> 5.0.0'
  pod 'FBSDKLoginKit', '~> 5.0.0'
  pod 'FBSDKShareKit', '~> 5.0.0'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end

target 'SideChore-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SideChore-tvOS

 

end
